# Generated by Django 4.0.5 on 2022-06-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_libro_idautor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='idAutor',
            new_name='autor',
        ),
    ]
